opam-version: "2.0"
maintainer:   "thomas@gazagnaire.org"
authors:      ["Thomas Gazagnaire" "Thomas Leonard"]
license:      "ISC"
homepage:     "https://github.com/mirage/irmin"
bug-reports:  "https://github.com/mirage/irmin/issues"
dev-repo:     "git+https://github.com/mirage/irmin.git"
doc:          "https://mirage.github.io/irmin/"

build: [
 ["dune" "subst"] {dev}
 ["dune" "build" "-p" name "-j" jobs]
 ["dune" "runtest" "-p" name "-j" jobs] {with-test}
]

depends: [
  "ocaml"           {>= "5.1.0"}
  "dune"            {>= "3.5.0"}
  "irmin-tezos"     {= version}
  "irmin-lwt"       {= version}
  "irmin-lwt-pack"  {= version}
  "lwt"             {>= "5.7.0"}
  "lwt_eio"         {>= "0.5.1"}
]

synopsis: """
Lwt-flavoured Tezos schema and pack store
"""
description: """
A Lwt shim exposing the Tezos-specific Irmin schema (Hash with
Base58 prefix, V1 pre-hashing for Node / Commit / Contents) on top of
[irmin-pack-unix], with a Lwt-typed Store API. Allows Lwt
applications to read / write Tezos-formatted data on disk.
"""
x-maintenance-intent: [ "(latest)" ]
