direction: down

irmin-fs -> irmin
irmin-git -> irmin
irmin-pack -> irmin
irmin-containers -> irmin
irmin-graphql -> irmin
irmin-server -> irmin
irmin-cli -> irmin
libirmin -> irmin
irmin-mirage -> irmin
irmin-tezos -> irmin

irmin-git -> ppx_irmin
irmin-server -> ppx_irmin
irmin-pack -> ppx_irmin
irmin-containers -> ppx_irmin
irmin-tezos -> ppx_irmin
irmin -> ppx_irmin

irmin-server -> irmin-watcher
irmin-git -> irmin-watcher
irmin-fs -> irmin-watcher
irmin-cli -> irmin-watcher

irmin-server -> irmin-pack
irmin-cli -> irmin-pack
irmin-tezos -> irmin-pack

irmin-containers -> irmin-fs
irmin-cli -> irmin-fs

irmin-cli -> irmin-git
irmin-mirage-git -> irmin-git

irmin-mirage-graphql -> irmin-mirage
irmin-mirage-git -> irmin-mirage

irmin-cli -> irmin-graphql
irmin-mirage-graphql -> irmin-graphql

irmin-cli -> irmin-server

libirmin -> irmin-cli

irmin-cli -> irmin-tezos

