module Source_code_position = struct
  type t = string * int * int * int
  (** The type of inclusive ranges of source code positions, as generated by the
      OCaml {!__POS__} macro. The 4-tuple components are 'file name', 'line
      number', 'column start' and 'column end' respectively. *)

  let pp ppf (fname, line_number, col_start, col_end) =
    Format.fprintf ppf "File %S, line %d, characters %d-%d" fname line_number
      col_start col_end

  let tag : t Logs.Tag.def =
    Logs.Tag.def "Source_code_position"
      ~doc:"The source code location at which the log entry was generated." pp
end
