description = "HTTP backend for Irmin"
version = "%%VERSION_NUM%%"
requires = "irmin cohttp.lwt-core webmachine"
archive(byte)   = "irmin-http.cma"
plugin(byte)    = "irmin-http.cma"
archive(native) = "irmin-http.cmxa"
plugin(native)  = "irmin-http.cmxs"
