name: Git Checks

on:
  pull_request:

jobs:
  block-fixup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@v2.0.0
